### ISSUE TITLE
New business rule required

### ISSUE THREAD

**Issue by cmonsalvec** [marolos/ISII-WORKSHOP_PAGOS_GASOLINERAS#2]
**Is your feature request related to a problem? Please describe.**

This feature is not related to a problem. It is related to a new policy of the organization. 

Based on the impact of the pandemic in the 2020 results, the board of the company has approved a new business rule (policy) beginning january 2021, that needs to be included in our product. 

**Describe the solution you'd like**

The new business rule establishes: If the customer is male, over 25 and younger than 45 then it is needed to subtract $100 from the base premium.

Therefore, we ask you to modify the premium calculation adding this new rule. 

**Describe alternatives you've considered**

There is no alternative to be considered.

**Additional context**

I will provide you with more information if needed

Best regards,

**Comment by stevenaraujo98** [comment]
Hi @cmonsalvec . We have received your issue and proceeded to reproduce it. We will attend to your problem in the shortest possible time

**Comment by stevenaraujo98** [comment]
We have proceeded to categorize the issue as "Issue reproduction".

**Comment by stevenaraujo98** [comment]
We will proceed to process the request, @KennyCamba  will be the assigned analyst, @miguelquo   will develop the solution, and @KennyCamba will perform the tests.

**Comment by KennyCamba** [comment]
Hi, I attach the corresponding analysis for the issue.
[Analysis.xlsx](https://github.com/marolos/ISII-WORKSHOP_PAGOS_GASOLINERAS/files/5846901/Analysis.xlsx)

**Comment by cmonsalvec** [comment]
Dear @KennyCamba , I do agree with the proposed time and resources required for the new feature. However, I do not agree when you mention that there are not changes to be introduced in the requirements specifications.

**Comment by KennyCamba** [comment]
Ok @cmonsalvec, I have proceeded to make the necessary corrections in the analysis document.
[Analysis.xlsx](https://github.com/marolos/ISII-WORKSHOP_PAGOS_GASOLINERAS/files/5850336/Analysis.xlsx)

**Comment by cmonsalvec** [comment]
Great, I do agree with the analysis, please continue with the development

**Comment by mibmol** [comment]
https://github.com/marolos/ISII-WORKSHOP_PAGOS_GASOLINERAS/blob/b79f211e4b54d147bd035f695a75d8fe78eee32b/ec.edu.espol.workshops.second/src/main/java/ec/edu/espol/workshops/second/CarInsurance.java#L30-L31

**Comment by KennyCamba** [comment]
Attached the test plan and its results.
[Tester.docx](https://github.com/marolos/ISII-WORKSHOP_PAGOS_GASOLINERAS/files/5852750/Tester.docx)

**Comment by cmonsalvec** [comment]
Dear @KennyCamba ,

Good to see that all the tests have passed. ¿What is the next step to have this new version of the product running?

**Comment by KennyCamba** [comment]
Dear @cmonsalvec ,

Please review the document with the acceptance testing plan and let me know if you agree with it.
[AcceptanceTestPlan.pdf](https://github.com/marolos/ISII-WORKSHOP_PAGOS_GASOLINERAS/files/5852928/AcceptanceTestPlan.pdf)

**Comment by cmonsalvec** [comment]
Dear @KennyCamba,

I am happy to see that all these tests have passed. We are looking forward using this new version of the product in our organization.

**Comment by KennyCamba** [comment]
Ok @cmonsalvec 

Thank you, if you want you can carry out the tests yourself. Attached is a guide with the steps to follow to run the tests using the cucumber tool
[Guide.pdf](https://github.com/marolos/ISII-WORKSHOP_PAGOS_GASOLINERAS/files/5853279/Guide.pdf)

**Comment by stevenaraujo98** [comment]
Dear @cmonsalvec , the solution has been completed and the programmer (@miguelquo ) will release the new software version for you.

**Comment by cmonsalvec** [comment]
Dear @KennyCamba, I don't understand, you already sent me the tests with their results, isn't it?

Dear @stevenaraujo98 thanks, we are looking forward @miguelquo instructions. However, @KennyCamba is asking me aobut some tests.

**Comment by stevenaraujo98** [comment]
Dear @cmonsalvec, @KennyCamba says that if you want to test yourself, you can use the guide. @miguelquo is writing the instructions for you.

**Comment by mibmol** [comment]
Dear @cmonsalvec the new version of the software have been released and can be downloaded [here](https://github.com/marolos/ISII-WORKSHOP_PAGOS_GASOLINERAS/releases/tag/1.0)
You can download either the zip or the tar file, which you have to decompress within you working directory.

The uncompressed files correspond to a gradle project and is ready to be opened with the eclipse IDE.

**Comment by stevenaraujo98** [comment]
Dear @cmonsalvec   
Have you been able to use the software? and Are you satisfied with the solution?

**Comment by cmonsalvec** [comment]
Dear @miguelquo ,

Thanks for the instructions, we will follow them to use the new code in our organization

**Comment by cmonsalvec** [comment]
Dear @stevenaraujo98 ,

Sorry, but I just answered @miguelquo thanking him for the instructions to use the software. So we are going to begin to use it in a few minutes. If you want you can ask me later on about the reactions.

Regards,

**Comment by stevenaraujo98** [comment]
Dear @cmonsalvec ,

Very good, I await your response after testing the system.
Thank you.

**Comment by cmonsalvec** [comment]
Dear @stevenaraujo98 ,

We are using the new version of the product without any problem, my organization is happy with the solution so far. Thanks.

**Comment by stevenaraujo98** [comment]
Dear @cmonsalvec,

We are very happy that you like it.
Thanks for everything.
